DROP TABLE IF EXISTS `test`;

CREATE TABLE `test` (
  `sum` TEXT NOT NULL DEFAULT 0,
  `count_fib` INT(11) UNSIGNED NOT NULL DEFAULT 0,
  `count_prime` INT(11) UNSIGNED NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `test` VALUES (0,0,0);